version: '3'
services:
  web:
    image: tanx-backend-crypto-price-alert-system-web
    build:
      context: .
    ports:
      - "5000:5000"  
    environment:
      DATABASE_URL: mysql+mysqlconnector://dbuser:dbpass@db/tanX_alert
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: new_root_password
      MYSQL_DATABASE: tanX_alert
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    ports:
      - "3306:3306" 